name: EmployeeAppAutomata

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d

      - name: Sleep for 75 seconds
        run: sleep 75s
        shell: bash

      - name: Collect docker logs
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'

      - name: Archive execution artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docker-logs
          path: './logs'

      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: ./postman-collections/employee_collection_28
          environment: ./postman-collections/employee28.postman_environment

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

